using System;
using System.Windows.Forms;

namespace PCODSurvey
{
    public partial class ResultForm : Form
    {
        private Label resultLabel;

        // Constructor that accepts the result message
        public ResultForm(string resultMessage)
        {
            InitializeComponent(); // Automatically generated by the Designer
            DisplayResult(resultMessage); // Pass the result message to the form
        }

        // Display the result message in a label
        private void DisplayResult(string resultMessage)
        {
            resultLabel = new Label();
            resultLabel.AutoSize = true;
            resultLabel.Location = new System.Drawing.Point(30, 30);
            resultLabel.Size = new System.Drawing.Size(500, 50);
            resultLabel.Text = resultMessage;
            resultLabel.Font = new System.Drawing.Font("Arial", 14);
            this.Controls.Add(resultLabel);
        }

        // Optional: Handle the form load event if needed
        private void ResultForm_Load(object sender, EventArgs e)
        {
            // Perform any logic you want when the form is loaded (if needed)
        }
    }
}
